manifest_version = "1"
id = "docusaurus-ssg"
description = "Template for Rancher docs using Spin and Docusaurus"

[add_component]
skip_files = ["spin.toml"]
skip_parameters = ["http-base"]
[add_component.snippets]
component = "component.txt"

[parameters]
project-description = { type = "string", prompt = "Project description", default = "" }
http-base = { type = "string", prompt = "HTTP base", default = "/", pattern = "^/\\S*$" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }
