spin_manifest_version = 2

[application]
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "0.1.0"

[[trigger.http]]
route = "{{http-path}}"
component = "{{project-name}}"

[component.{{project-name}}]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "sample/build/", destination = "/" }]
exclude_files = ["**/node_modules"]
environment = { FALLBACK_PATH ="index.html" }

[component.{{project-name}}.build]
watch = ["src/"]
command = "npm install && npm run build"
workdir = "sample"
