spin_manifest_version = 2

[application]
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "{{project-name}}"

[component.{{project-name}}]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "sample/build/", destination = "/" }]
exclude_files = ["**/node_modules"]
environment = { FALLBACK_PATH ="index.html" }

[component.{{project-name}}.build]
watch = ["src/"]
command = "npm install && npm run build"
workdir = "sample"
